### ISSUE TITLE
Pregunta acerca del progtama

### ISSUE THREAD

**Issue by Carlos1801011** [Gaspipi/HistoriaClinica#4]
Talvez puedas remitir tu correo o tu discord estoy interesado en este modelo

**Comment by Carlos1801011** [comment]
?

**Comment by Gaspipi** [comment]
Buen día! Podes contactarme a través de LinkedIn. En mi perfil están mis enlaces de contacto!

**Comment by Carlos1801011** [comment]
Buen dia gaspipi! No me sale nada en tu perfil, si podrias proporcionar tu nombre en linkedln ?

**Comment by Gaspipi** [comment]
Ya te agregué en Discord!
